### ISSUE TITLE
Create a post form

### ISSUE THREAD

**Issue by Archie1008** [rpaulin90/Project-2#4]
Create and integrate a "create a post" form into handlebars.

**Comment by rpaulin90** [comment]
section included successfully. Next steps:

- How do we make a field where a user can upload an image file from their computer?
- How do we store that image in a remote database (see the link that Erick sent us yesterday)?
- How can we store that in our mysql database?
- How can we retrieve that image using a link?

**Comment by Archie1008** [comment]
I will open the next issue for that
